version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
    ports:
      - "8801:80"
    networks:
      - php
  php:
    image: php:fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - php
networks:
  php:
    driver: bridge
